apiVersion: v1
kind: Template
labels:
  template: osio-hypothesis-istio-poc
metadata:
  name: osio-hypothesis-istio-poc
  annotations:
    description: ${APP_NAME}
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
          - image: >-
              anmolb/istio-poc:latest
            imagePullPolicy: Always
            name: ${APP_NAME}
            env:
            - name: BEARER_STR
              value: ${BEARER_STR}
            - name: IN_CLUSTER_CONFIG
              value: ${IN_CLUSTER_CONFIG}
            readinessProbe:
              httpGet:
                path: /readiness
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 60
              timeoutSeconds: 10
            livenessProbe:
              httpGet:
                path: /liveness
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 60
              timeoutSeconds: 10
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "1024Mi"
                cpu: "1000m"
            securityContext:
              privileged: false
      triggers:
        - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
      - name: ${APP_NAME}
        port: 8000
        protocol: TCP
        targetPort: 8000
    selector:
      app: ${APP_NAME}
parameters:
- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"
- description: Name of the app
  displayName: Name of the app
  required: true
  name: APP_NAME
  value: "osio-hypothesis-istio-poc"
- description: Route path
  displayName: Route path
  required: true
  name: ROUTE_PATH
  value: "/manager"
- description: Route prefix
  displayName: Route prefix
  required: true
  name: ROUTE_PREFIX
  value: "/api/v1.0"
- description: BEARER STRING
  displayName: BEARER STRING
  required: true
  name: BEARER_STR
  value: "5y9JD52WY4h6qByNdAUSx_8aBxmxMO1B-9CKCRDB6zg"
- description: In Cluster config
  displayName: In Cluster config
  required: true
  name: IN_CLUSTER_CONFIG
  value: "true"